In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [48]:
data = pd.read_csv('1082591.csv',header=None,names = list(range(0,11)))

In [54]:
innings = pd.DataFrame(columns=['inning','over','batting_team_name','batsman','non-striker','bowler','runs_off_bat','Extras','Kind of wicket','Dismissed player'])

In [51]:
innings

Empty DataFrame
Columns: [inning, over, batting_team_name, batsman, non-striker, bowler, runs_off_bat, Extras, Kind of wicket, Dismissed player]
Index: []

In [52]:
data.columns=['ball','inning','over','batting_team_name','batsman','non-striker','bowler','runs_off_bat','Extras','Kind of wicket','Dismissed player']
data=data[data['ball']=='ball']
data=data[['inning','over','batting_team_name','batsman','non-striker','bowler','runs_off_bat','Extras','Kind of wicket','Dismissed player']]
innings=innings.merge(data,how='outer')

In [53]:
innings

,inning,over,batting_team_name,batsman,non-striker,bowler,runs_off_bat,Extras,Kind of wicket,Dismissed player
0,1,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
1,1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
2,1,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4.0,0.0,NaN,NaN
3,1,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
4,1,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,2.0,NaN,NaN
5,1,0.6,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0.0,0.0,NaN,NaN
6,1,0.7,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0.0,1.0,NaN,NaN
7,1,1.1,Sunrisers Hyderabad,S Dhawan,DA Warner,A Choudhary,1.0,0.0,NaN,NaN
8,1,1.2,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,4.0,0.0,NaN,NaN
9,1,1.3,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0.0,1.0,NaN,NaN
10,1,1.4,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,6.0,0.0,NaN,NaN
11,1,1.5,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0.0,0.0,caught,DA Warner
12,1,1.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,0.0,0.0,NaN,NaN
13,1,1.7,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,4.0,0.0,NaN,NaN
14,1,2.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1.0,0.0,NaN,NaN
15,1,2.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
16,1,2.3,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
17,1,2.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,3.0,0.0,NaN,NaN
18,1,2.5,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1.0,0.0,NaN,NaN
19,1,2.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,1.0,0.0,NaN,NaN
20,1,3.1,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,0.0,0.0,NaN,NaN
21,1,3.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1.0,0.0,NaN,NaN
22,1,3.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,0.0,0.0,NaN,NaN
23,1,3.4,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1.0,0.0,NaN,NaN
24,1,3.5,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1.0,0.0,NaN,NaN
25,1,3.6,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1.0,0.0,NaN,NaN
26,1,4.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1.0,0.0,NaN,NaN
27,1,4.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,1.0,0.0,NaN,NaN
28,1,4.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1.0,0.0,NaN,NaN
29,1,4.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,2.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
218,2,14.5,Royal Challengers Bangalore,STR Binny,SR Watson,Rashid Khan,1.0,0.0,NaN,NaN
219,2,14.6,Royal Challengers Bangalore,SR Watson,STR Binny,Rashid Khan,6.0,0.0,NaN,NaN
220,2,15.1,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,0.0,0.0,NaN,NaN
221,2,15.2,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,6.0,0.0,NaN,NaN
222,2,15.3,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,1.0,0.0,NaN,NaN
223,2,15.4,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,0.0,0.0,NaN,NaN
224,2,15.5,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,4.0,0.0,NaN,NaN
225,2,15.6,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,1.0,0.0,NaN,NaN
226,2,16.1,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,1.0,0.0,NaN,NaN
227,2,16.2,Royal Challengers Bangalore,STR Binny,SR Watson,B Kumar,1.0,0.0,NaN,NaN
228,2,16.3,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,0.0,0.0,NaN,NaN
229,2,16.4,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,1.0,0.0,NaN,NaN
230,2,16.5,Royal Challengers Bangalore,STR Binny,SR Watson,B Kumar,0.0,0.0,caught,STR Binny
231,2,16.6,Royal Challengers Bangalore,S Aravind,SR Watson,B Kumar,0.0,0.0,NaN,NaN
232,2,17.1,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,2.0,0.0,NaN,NaN
233,2,17.2,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,0.0,0.0,NaN,NaN
234,2,17.3,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,0.0,0.0,caught,SR Watson
235,2,17.4,Royal Challengers Bangalore,S Aravind,TS Mills,A Nehra,0.0,0.0,bowled,S Aravind
236,2,17.5,Royal Challengers Bangalore,YS Chahal,TS Mills,A Nehra,0.0,0.0,NaN,NaN
237,2,17.6,Royal Challengers Bangalore,YS Chahal,TS Mills,A Nehra,0.0,0.0,NaN,NaN
238,2,18.1,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,0.0,1.0,NaN,NaN
239,2,18.2,Royal Challengers Bangalore,YS Chahal,TS Mills,B Kumar,0.0,0.0,NaN,NaN
240,2,18.3,Royal Challengers Bangalore,YS Chahal,TS Mills,B Kumar,1.0,0.0,NaN,NaN
241,2,18.4,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,6.0,0.0,NaN,NaN
242,2,18.5,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,0.0,0.0,caught,TS Mills
243,2,18.6,Royal Challengers Bangalore,YS Chahal,A Choudhary,B Kumar,1.0,0.0,NaN,NaN
244,2,19.1,Royal Challengers Bangalore,YS Chahal,A Choudhary,BCJ Cutting,0.0,0.0,NaN,NaN
245,2,19.2,Royal Challengers Bangalore,YS Chahal,A Choudhary,BCJ Cutting,1.0,0.0,NaN,NaN
246,2,19.3,Royal Challengers Bangalore,A Choudhary,YS Chahal,BCJ Cutting,6.0,0.0,NaN,NaN
247,2,19.4,Royal Challengers Bangalore,A Choudhary,YS Chahal,BCJ Cutting,0.0,0.0,run out,YS Chahal

In [33]:
data[data['a']=='ball']

,a,b,c,d,e,f,g,h,i,j,k
20,ball,1,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
21,ball,1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
22,ball,1,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4.0,0.0,NaN,NaN
23,ball,1,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
24,ball,1,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,2.0,NaN,NaN
25,ball,1,0.6,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0.0,0.0,NaN,NaN
26,ball,1,0.7,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0.0,1.0,NaN,NaN
27,ball,1,1.1,Sunrisers Hyderabad,S Dhawan,DA Warner,A Choudhary,1.0,0.0,NaN,NaN
28,ball,1,1.2,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,4.0,0.0,NaN,NaN
29,ball,1,1.3,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0.0,1.0,NaN,NaN
30,ball,1,1.4,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,6.0,0.0,NaN,NaN
31,ball,1,1.5,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0.0,0.0,caught,DA Warner
32,ball,1,1.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,0.0,0.0,NaN,NaN
33,ball,1,1.7,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,4.0,0.0,NaN,NaN
34,ball,1,2.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1.0,0.0,NaN,NaN
35,ball,1,2.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
36,ball,1,2.3,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
37,ball,1,2.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,3.0,0.0,NaN,NaN
38,ball,1,2.5,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1.0,0.0,NaN,NaN
39,ball,1,2.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,1.0,0.0,NaN,NaN
40,ball,1,3.1,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,0.0,0.0,NaN,NaN
41,ball,1,3.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1.0,0.0,NaN,NaN
42,ball,1,3.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,0.0,0.0,NaN,NaN
43,ball,1,3.4,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1.0,0.0,NaN,NaN
44,ball,1,3.5,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1.0,0.0,NaN,NaN
45,ball,1,3.6,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1.0,0.0,NaN,NaN
46,ball,1,4.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1.0,0.0,NaN,NaN
47,ball,1,4.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,1.0,0.0,NaN,NaN
48,ball,1,4.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1.0,0.0,NaN,NaN
49,ball,1,4.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,2.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
238,ball,2,14.5,Royal Challengers Bangalore,STR Binny,SR Watson,Rashid Khan,1.0,0.0,NaN,NaN
239,ball,2,14.6,Royal Challengers Bangalore,SR Watson,STR Binny,Rashid Khan,6.0,0.0,NaN,NaN
240,ball,2,15.1,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,0.0,0.0,NaN,NaN
241,ball,2,15.2,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,6.0,0.0,NaN,NaN
242,ball,2,15.3,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,1.0,0.0,NaN,NaN
243,ball,2,15.4,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,0.0,0.0,NaN,NaN
244,ball,2,15.5,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,4.0,0.0,NaN,NaN
245,ball,2,15.6,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,1.0,0.0,NaN,NaN
246,ball,2,16.1,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,1.0,0.0,NaN,NaN
247,ball,2,16.2,Royal Challengers Bangalore,STR Binny,SR Watson,B Kumar,1.0,0.0,NaN,NaN
248,ball,2,16.3,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,0.0,0.0,NaN,NaN
249,ball,2,16.4,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,1.0,0.0,NaN,NaN
250,ball,2,16.5,Royal Challengers Bangalore,STR Binny,SR Watson,B Kumar,0.0,0.0,caught,STR Binny
251,ball,2,16.6,Royal Challengers Bangalore,S Aravind,SR Watson,B Kumar,0.0,0.0,NaN,NaN
252,ball,2,17.1,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,2.0,0.0,NaN,NaN
253,ball,2,17.2,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,0.0,0.0,NaN,NaN
254,ball,2,17.3,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,0.0,0.0,caught,SR Watson
255,ball,2,17.4,Royal Challengers Bangalore,S Aravind,TS Mills,A Nehra,0.0,0.0,bowled,S Aravind
256,ball,2,17.5,Royal Challengers Bangalore,YS Chahal,TS Mills,A Nehra,0.0,0.0,NaN,NaN
257,ball,2,17.6,Royal Challengers Bangalore,YS Chahal,TS Mills,A Nehra,0.0,0.0,NaN,NaN
258,ball,2,18.1,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,0.0,1.0,NaN,NaN
259,ball,2,18.2,Royal Challengers Bangalore,YS Chahal,TS Mills,B Kumar,0.0,0.0,NaN,NaN
260,ball,2,18.3,Royal Challengers Bangalore,YS Chahal,TS Mills,B Kumar,1.0,0.0,NaN,NaN
261,ball,2,18.4,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,6.0,0.0,NaN,NaN
262,ball,2,18.5,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,0.0,0.0,caught,TS Mills
263,ball,2,18.6,Royal Challengers Bangalore,YS Chahal,A Choudhary,B Kumar,1.0,0.0,NaN,NaN
264,ball,2,19.1,Royal Challengers Bangalore,YS Chahal,A Choudhary,BCJ Cutting,0.0,0.0,NaN,NaN
265,ball,2,19.2,Royal Challengers Bangalore,YS Chahal,A Choudhary,BCJ Cutting,1.0,0.0,NaN,NaN
266,ball,2,19.3,Royal Challengers Bangalore,A Choudhary,YS Chahal,BCJ Cutting,6.0,0.0,NaN,NaN
267,ball,2,19.4,Royal Challengers Bangalore,A Choudhary,YS Chahal,BCJ Cutting,0.0,0.0,run out,YS Chahal

In [34]:
import os
files = os.listdir()

In [35]:
import re
cricfiles=re.findall(r'[\w]+.csv',' '.join(files))

In [55]:
for i in range(len(cricfiles)):
    data = pd.read_csv(cricfiles[i],header=None,names = list(range(0,11)))
    data.columns=['ball','inning','over','batting_team_name','batsman','non-striker','bowler','runs_off_bat','Extras','Kind of wicket','Dismissed player']
    data=data[data['ball']=='ball']
    data=data[['inning','over','batting_team_name','batsman','non-striker','bowler','runs_off_bat','Extras','Kind of wicket','Dismissed player']]
    innings=innings.merge(data,how='outer')

In [106]:
innings.to_csv('innings.csv')

In [45]:
data

,ball,inning,over,batting_team_name,batsman,non-striker,bowler,runs_off_bat,Extras,Kind of wicket,Dismissed player
20,ball,1,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
21,ball,1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
22,ball,1,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4.0,0.0,NaN,NaN
23,ball,1,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
24,ball,1,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,2.0,NaN,NaN
25,ball,1,0.6,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0.0,0.0,NaN,NaN
26,ball,1,0.7,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0.0,1.0,NaN,NaN
27,ball,1,1.1,Sunrisers Hyderabad,S Dhawan,DA Warner,A Choudhary,1.0,0.0,NaN,NaN
28,ball,1,1.2,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,4.0,0.0,NaN,NaN
29,ball,1,1.3,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0.0,1.0,NaN,NaN
30,ball,1,1.4,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,6.0,0.0,NaN,NaN
31,ball,1,1.5,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0.0,0.0,caught,DA Warner
32,ball,1,1.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,0.0,0.0,NaN,NaN
33,ball,1,1.7,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,4.0,0.0,NaN,NaN
34,ball,1,2.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1.0,0.0,NaN,NaN
35,ball,1,2.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
36,ball,1,2.3,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0.0,0.0,NaN,NaN
37,ball,1,2.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,3.0,0.0,NaN,NaN
38,ball,1,2.5,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1.0,0.0,NaN,NaN
39,ball,1,2.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,1.0,0.0,NaN,NaN
40,ball,1,3.1,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,0.0,0.0,NaN,NaN
41,ball,1,3.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1.0,0.0,NaN,NaN
42,ball,1,3.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,0.0,0.0,NaN,NaN
43,ball,1,3.4,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1.0,0.0,NaN,NaN
44,ball,1,3.5,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1.0,0.0,NaN,NaN
45,ball,1,3.6,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1.0,0.0,NaN,NaN
46,ball,1,4.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1.0,0.0,NaN,NaN
47,ball,1,4.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,1.0,0.0,NaN,NaN
48,ball,1,4.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1.0,0.0,NaN,NaN
49,ball,1,4.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,2.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
238,ball,2,14.5,Royal Challengers Bangalore,STR Binny,SR Watson,Rashid Khan,1.0,0.0,NaN,NaN
239,ball,2,14.6,Royal Challengers Bangalore,SR Watson,STR Binny,Rashid Khan,6.0,0.0,NaN,NaN
240,ball,2,15.1,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,0.0,0.0,NaN,NaN
241,ball,2,15.2,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,6.0,0.0,NaN,NaN
242,ball,2,15.3,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,1.0,0.0,NaN,NaN
243,ball,2,15.4,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,0.0,0.0,NaN,NaN
244,ball,2,15.5,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,4.0,0.0,NaN,NaN
245,ball,2,15.6,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,1.0,0.0,NaN,NaN
246,ball,2,16.1,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,1.0,0.0,NaN,NaN
247,ball,2,16.2,Royal Challengers Bangalore,STR Binny,SR Watson,B Kumar,1.0,0.0,NaN,NaN
248,ball,2,16.3,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,0.0,0.0,NaN,NaN
249,ball,2,16.4,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,1.0,0.0,NaN,NaN
250,ball,2,16.5,Royal Challengers Bangalore,STR Binny,SR Watson,B Kumar,0.0,0.0,caught,STR Binny
251,ball,2,16.6,Royal Challengers Bangalore,S Aravind,SR Watson,B Kumar,0.0,0.0,NaN,NaN
252,ball,2,17.1,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,2.0,0.0,NaN,NaN
253,ball,2,17.2,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,0.0,0.0,NaN,NaN
254,ball,2,17.3,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,0.0,0.0,caught,SR Watson
255,ball,2,17.4,Royal Challengers Bangalore,S Aravind,TS Mills,A Nehra,0.0,0.0,bowled,S Aravind
256,ball,2,17.5,Royal Challengers Bangalore,YS Chahal,TS Mills,A Nehra,0.0,0.0,NaN,NaN
257,ball,2,17.6,Royal Challengers Bangalore,YS Chahal,TS Mills,A Nehra,0.0,0.0,NaN,NaN
258,ball,2,18.1,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,0.0,1.0,NaN,NaN
259,ball,2,18.2,Royal Challengers Bangalore,YS Chahal,TS Mills,B Kumar,0.0,0.0,NaN,NaN
260,ball,2,18.3,Royal Challengers Bangalore,YS Chahal,TS Mills,B Kumar,1.0,0.0,NaN,NaN
261,ball,2,18.4,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,6.0,0.0,NaN,NaN
262,ball,2,18.5,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,0.0,0.0,caught,TS Mills
263,ball,2,18.6,Royal Challengers Bangalore,YS Chahal,A Choudhary,B Kumar,1.0,0.0,NaN,NaN
264,ball,2,19.1,Royal Challengers Bangalore,YS Chahal,A Choudhary,BCJ Cutting,0.0,0.0,NaN,NaN
265,ball,2,19.2,Royal Challengers Bangalore,YS Chahal,A Choudhary,BCJ Cutting,1.0,0.0,NaN,NaN
266,ball,2,19.3,Royal Challengers Bangalore,A Choudhary,YS Chahal,BCJ Cutting,6.0,0.0,NaN,NaN
267,ball,2,19.4,Royal Challengers Bangalore,A Choudhary,YS Chahal,BCJ Cutting,0.0,0.0,run out,YS Chahal

In [90]:

c=1
for i in range(innings.shape[0]-1):
    if ((innings['inning'][i]=='1') and (innings['inning'][i+1]=='1' or innings['inning'][i+1]=='2')) or ((innings['inning'][i]=='2') and (innings['inning'][i+1]=='2')):
        innings['match_id'][i]=c
    else:
        c=c+1
        innings['match_id'][i]=c

C:\Users\Devansh\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Devansh\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [103]:
innings.iloc[150139:150140,:]['match_id']=715

C:\Users\Devansh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,inning,over,batting_team_name,batsman,non-striker,bowler,runs_off_bat,Extras,Kind of wicket,Dismissed player,match_id
0,1,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN,1
1,1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN,1
2,1,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4.0,0.0,NaN,NaN,1
3,1,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,0.0,NaN,NaN,1
4,1,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0.0,2.0,NaN,NaN,1
5,1,0.6,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0.0,0.0,NaN,NaN,1
6,1,0.7,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0.0,1.0,NaN,NaN,1
7,1,1.1,Sunrisers Hyderabad,S Dhawan,DA Warner,A Choudhary,1.0,0.0,NaN,NaN,1
8,1,1.2,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,4.0,0.0,NaN,NaN,1
9,1,1.3,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0.0,1.0,NaN,NaN,1
10,1,1.4,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,6.0,0.0,NaN,NaN,1
11,1,1.5,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0.0,0.0,caught,DA Warner,1
12,1,1.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,0.0,0.0,NaN,NaN,1
13,1,1.7,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,4.0,0.0,NaN,NaN,1
14,1,2.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1.0,0.0,NaN,NaN,1
15,1,2.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0.0,0.0,NaN,NaN,1
16,1,2.3,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0.0,0.0,NaN,NaN,1
17,1,2.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,3.0,0.0,NaN,NaN,1
18,1,2.5,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1.0,0.0,NaN,NaN,1
19,1,2.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,1.0,0.0,NaN,NaN,1
20,1,3.1,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,0.0,0.0,NaN,NaN,1
21,1,3.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1.0,0.0,NaN,NaN,1
22,1,3.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,0.0,0.0,NaN,NaN,1
23,1,3.4,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1.0,0.0,NaN,NaN,1
24,1,3.5,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1.0,0.0,NaN,NaN,1
25,1,3.6,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1.0,0.0,NaN,NaN,1
26,1,4.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1.0,0.0,NaN,NaN,1
27,1,4.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,1.0,0.0,NaN,NaN,1
28,1,4.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1.0,0.0,NaN,NaN,1
29,1,4.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,2.0,0.0,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
150060,2,6.6,Royal Challengers Bangalore,V Kohli,CH Gayle,MC Henriques,1.0,0.0,NaN,NaN,715
150061,2,7.1,Royal Challengers Bangalore,V Kohli,CH Gayle,BCJ Cutting,0.0,0.0,NaN,NaN,715
150062,2,7.2,Royal Challengers Bangalore,V Kohli,CH Gayle,BCJ Cutting,1.0,0.0,NaN,NaN,715
150063,2,7.3,Royal Challengers Bangalore,CH Gayle,V Kohli,BCJ Cutting,0.0,1.0,NaN,NaN,715
150064,2,7.4,Royal Challengers Bangalore,CH Gayle,V Kohli,BCJ Cutting,6.0,0.0,NaN,NaN,715
150065,2,7.5,Royal Challengers Bangalore,CH Gayle,V Kohli,BCJ Cutting,0.0,0.0,NaN,NaN,715
150066,2,7.6,Royal Challengers Bangalore,CH Gayle,V Kohli,BCJ Cutting,1.0,0.0,NaN,NaN,715
150067,2,7.7,Royal Challengers Bangalore,V Kohli,CH Gayle,BCJ Cutting,1.0,0.0,NaN,NaN,715
150068,2,8.1,Royal Challengers Bangalore,V Kohli,CH Gayle,MC Henriques,4.0,0.0,NaN,NaN,715
150069,2,8.2,Royal Challengers Bangalore,V Kohli,CH Gayle,MC Henriques,1.0,0.0,NaN,NaN,715
150070,2,8.3,Royal Challengers Bangalore,CH Gayle,V Kohli,MC Henriques,0.0,0.0,NaN,NaN,715
150071,2,8.4,Royal Challengers Bangalore,CH Gayle,V Kohli,MC Henriques,6.0,0.0,NaN,NaN,715
150072,2,8.5,Royal Challengers Bangalore,CH Gayle,V Kohli,MC Henriques,6.0,0.0,NaN,NaN,715
150073,2,8.6,Royal Challengers Bangalore,CH Gayle,V Kohli,MC Henriques,4.0,0.0,NaN,NaN,715
150074,2,9.1,Royal Challengers Bangalore,V Kohli,CH Gayle,Mustafizur Rahman,4.0,0.0,NaN,NaN,715
150075,2,9.2,Royal Challengers Bangalore,V Kohli,CH Gayle,Mustafizur Rahman,6.0,0.0,NaN,NaN,715
150076,2,9.3,Royal Challengers Bangalore,V Kohli,CH Gayle,Mustafizur Rahman,1.0,0.0,NaN,NaN,715
150077,2,9.4,Royal Challengers Bangalore,CH Gayle,V Kohli,Mustafizur Rahman,0.0,0.0,NaN,NaN,715
150078,2,9.5,Royal Challengers Bangalore,CH Gayle,V Kohli,Mustafizur Rahman,1.0,0.0,NaN,NaN,715
150079,2,9.6,Royal Challengers Bangalore,V Kohli,CH Gayle,Mustafizur Rahman,0.0,0.0,NaN,NaN,715
150080,2,10.1,Royal Challengers Bangalore,CH Gayle,V Kohli,BCJ Cutting,1.0,0.0,NaN,NaN,715
150081,2,10.2,Royal Challengers Bangalore,V Kohli,CH Gayle,BCJ Cutting,1.0,0.0,NaN,NaN,715
150082,2,10.3,Royal Challengers Bangalore,CH Gayle,V Kohli,BCJ Cutting,0.0,0.0,caught,CH Gayle,715
150083,2,10.4,Royal Challengers Bangalore,V Kohli,AB de Villiers,BCJ Cutting,4.0,0.0,NaN,NaN,715
150084,2,10.5,Royal Challengers Bangalore,V Kohli,AB de Villiers,BCJ Cutting,2.0,0.0,NaN,NaN,715
150085,2,10.6,Royal Challengers Bangalore,V Kohli,AB de Villiers,BCJ Cutting,0.0,0.0,NaN,NaN,715
150086,2,11.1,Royal Challengers Bangalore,AB de Villiers,V Kohli,Bipul Sharma,1.0,0.0,NaN,NaN,715
150087,2,11.2,Royal Challengers Bangalore,V Kohli,AB de Villiers,Bipul Sharma,4.0,0.0,NaN,NaN,715
150088,2,11.3,Royal Challengers Bangalore,V Kohli,AB de Villiers,Bipul Sharma,1.0,0.0,NaN,NaN,715
150089,2,11.4,Royal Challengers Bangalore,AB de Villiers,V Kohli,Bipul Sharma,1.0,0.0,NaN,NaN,715

In [105]:
innings['match_id'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
       248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
       326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
       339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,
       352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364,
       365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377,
       378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390,
       391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403,
       404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416,
       417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429,
       430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442,
       443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455,
       456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468,
       469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481,
       482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494,
       495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507,
       508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520,
       521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533,
       534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546,
       547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559,
       560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572,
       573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585,
       586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598,
       599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611,
       612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624,
       625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637,
       638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650,
       651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663,
       664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676,
       677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689,
       690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702,
       703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715],
      dtype=int64)

In [93]:
c

715

In [95]:
innings[innings['match_id']<=c].shape[0]

150140

In [94]:
innings[innings['match_id']!=0].shape[0]

150139

In [81]:
150140-33611

116529